name: extra_pedantic
version: 1.5.0
description: >-
  The Dart analyzer settings and best practices used internally at I.C.N.H GmbH.
repository: https://github.com/icnh/flutter_packages/tree/master/extra_pedantic

environment:
    sdk: '>=2.19.0 <4.0.0'
