name: styled_text
description: A widget to easily create `RichText` from a string
version: 0.1.0
repository: https://github.com/icnh/flutter_packages/tree/master/styled_text

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
