name: value_builder
description: A simple observable variable for Flutter
version: 0.1.0
authors:
 - Stefan Matthias Aust <sma@icnh.de>
homepage: https://bitbucket.org/icnh/flutter_packages/value_builder/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
